### ISSUE TITLE
OSError: [Errno 36] File name too long

### ISSUE THREAD

**Issue by canfirtina** [felicityallen/SelfTarget#16]
Hi @felicityallen,

I have the following issue when running FORECasT in Docker.

`Traceback (most recent call last):
  File "FORECasT.py", line 29, in <module>
    predictMutationsSingle(target_seq, pam_idx, output_prefix)
  File "/usr/local/lib/python3.6/site-packages/predictor/predict.py", line 138, in predictMutationsSingle
    p_predict, rep_reads, in_frame_perc = predictMutations(theta_file, target_seq, pam_idx)
  File "/usr/local/lib/python3.6/site-packages/predictor/predict.py", line 51, in predictMutations
    rep_reads = fetchRepReads(tmp_genindels_file)
  File "/usr/local/lib/python3.6/site-packages/predictor/predict.py", line 23, in fetchRepReads
    f = io.open(genindels_file)
OSError: [Errno 36] File name too long: 'tmp_genindels_CACTCACGCACACTCGTACTGAGACTCAAGGCCGTCTCCACAACTCCAACCAGTGCAAATGACTTAGTGCAAATTAAATTCAGAAGGGACGGGGGAAACAGAGTCGTGGAGGCTTTGAATCTCTCAGAAAAAAGGAAAGACAGGAAAGCTCAGAAACAAAGAGACAGAAGGATGAAAAAGAAGAAGAGGGAGGTGGTGGGGACGGCGTCATCCCGCTGGAGGAGCTCAGCTCTGGGATGATGTGGTGGCTGGTGGTCAACCGTCCGCCGCAGGGGGTGGCCATGAAGATGGAGTCGCCGGTGCGGGGTGGGTGCTGCGGGCGCTGCTGTTCCGATGGTGTCTTTGATGTTGGGCTGATGAGGTCTGGTTCCTCTAGCTTCACCTAGAGATAGCGACACGTGGGTGGGATGGGGGCAGGGTGCTCGGGGGCCTGGAGGCTTCCGGAAGGAGCGCTGGTGCTCACCTTCCAGAGCCGATTCCTGAGTCAGGTAGTGCAGTGGTTGTAAAGTGCAGCATATTCATT_22081.txt'`

I used the following command:

`python FORECasT.py CACTCACGCACACTCGTACTGAGACTCAAGGCCGTCTCCACAACTCCAACCAGTGCAAATGACTTAGTGCAAATTAAATTCAGAAGGGACGGGGGAAACAGAGTCGTGGAGGCTTTGAATCTCTCAGAAAAAAGGAAAGACAGGAAAGCTCAGAAACAAAGAGACAGAAGGATGAAAAAGAAGAAGAGGGAGGTGGTGGGGACGGCGTCATCCCGCTGGAGGAGCTCAGCTCTGGGATGATGTGGTGGCTGGTGGTCAACCGTCCGCCGCAGGGGGTGGCCATGAAGATGGAGTCGCCGGTGCGGGGTGGGTGCTGCGGGCGCTGCTGTTCCGATGGTGTCTTTGATGTTGGGCTGATGAGGTCTGGTTCCTCTAGCTTCACCTAGAGATAGCGACACGTGGGTGGGATGGGGGCAGGGTGCTCGGGGGCCTGGAGGCTTCCGGAAGGAGCGCTGGTGCTCACCTTCCAGAGCCGATTCCTGAGTCAGGTAGTGCAGTGGTTGTAAAGTGCAGCATATTCATT 270 .`

It may not be a good idea to concatenate the sequence itself as filename as for large target sequences this becomes an issue.

**Comment by felicityallen** [comment]
Couldn't agree more. I've fixed this. Thanks for flagging it.
